# Generated by Django 4.2.30 on 2026-05-14 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveSmallIntegerField(default=7, help_text='Number of days to boost the post (1–30)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid (DA or equivalent)', max_digits=10)),
                ('payment_method', models.CharField(choices=[('balance', 'Account Balance'), ('ccp', 'CCP / Postal Account'), ('baridimob', 'BaridiMob'), ('dahabiya', 'Dahabiya Card')], default='balance', max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='Wallet ID or account number (simulated)', max_length=30)),
                ('pin_hash', models.CharField(blank=True, help_text='SHA-256 hash of user-supplied PIN (never plain)', max_length=128)),
                ('target_country', models.CharField(blank=True, default='', max_length=100)),
                ('target_city', models.CharField(blank=True, default='', max_length=100)),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('farmer', 'Farmers Only'), ('company', 'Companies Only'), ('expert', 'Experts Only'), ('user', 'General Users')], default='all', max_length=20)),
                ('target_interest', models.CharField(choices=[('all', 'All Interests'), ('pesticides', 'Medicines / Pesticides'), ('crops', 'Crops / Agriculture Products'), ('equipment', 'Equipment / Machinery'), ('fertilizers', 'Fertilizers'), ('general', 'General Farming')], default='all', max_length=30)),
                ('boost_score', models.FloatField(default=0.0, help_text='Computed boost weight used in feed ranking')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='community.post')),
                ('promoted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoted Post',
                'verbose_name_plural': 'Promoted Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'end_date'], name='community_p_status_632d97_idx'), models.Index(fields=['target_role'], name='community_p_target__fbe2e7_idx'), models.Index(fields=['target_country', 'target_city'], name='community_p_target__d5c4af_idx')],
            },
        ),
    ]
