# Generated by Django 6.0.3 on 2026-05-31 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_promoted_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ad',
            field=models.BooleanField(default=False, help_text='True when this post has an active paid promotion (boosted/sponsored).'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_ad'], name='community_p_is_ad_69e0a3_idx'),
        ),
    ]
