# Generated by Django 5.2.11 on 2026-03-12 15:41

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.CharField(choices=[('farmer', 'Mozari3'), ('company', 'Sharika'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(default=analysis.models.generate_user_code, max_length=6, unique=True),
        ),
    ]
