# Generated by Django 5.2.11 on 2026-03-12 16:46

import analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_rename_date_birth_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(default=analysis.models.generate_photo_id, max_length=12, unique=True)),
                ('folder_name', models.CharField(max_length=120)),
                ('image_original', models.ImageField(upload_to='scans/original/')),
                ('image_gradcam', models.ImageField(upload_to='scans/gradcam/')),
                ('prediction', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('disease_ratio', models.FloatField()),
                ('disease_stage', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
