# Generated by Django 5.2.11 on 2026-03-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_scanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='ai_economic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ai_irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ai_medical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='ai_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='fungicides_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='yield_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='disease_stage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='photo_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='prediction',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
