# Generated by Django 5.2.11 on 2026-03-25 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_scanresult_ai_economic_scanresult_ai_irrigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.CharField(max_length=50, unique=True)),
                ('new_image', models.ImageField(upload_to='followups/')),
                ('new_gradcam', models.ImageField(upload_to='followups/')),
                ('disease', models.CharField(max_length=120)),
                ('confidence', models.FloatField()),
                ('ratio', models.FloatField()),
                ('stage', models.CharField(max_length=50)),
                ('yield_loss', models.FloatField()),
                ('evolution_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_scans', to='analysis.scanresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
