# Generated by Django 6.0.4 on 2026-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_followupscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='followupscan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Follow-Up Scan', 'verbose_name_plural': 'Follow-Up Scans'},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scan Result', 'verbose_name_plural': 'Scan Results'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('company', 'Company'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
