# Generated by Django 6.0.4 on 2026-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_customuser_options_alter_followupscan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupscan',
            name='ai_economic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_medical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
