# Generated by Django 6.0.3 on 2026-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_followupscan_ai_economic_followupscan_ai_irrigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupscan',
            name='ai_economic',
        ),
        migrations.RemoveField(
            model_name='followupscan',
            name='ai_irrigation',
        ),
        migrations.RemoveField(
            model_name='followupscan',
            name='ai_medical',
        ),
        migrations.RemoveField(
            model_name='followupscan',
            name='ai_treatment',
        ),
    ]
