# Generated by Django 6.0.3 on 2026-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_remove_followupscan_ai_economic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupscan',
            name='ai_economic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_medical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupscan',
            name='ai_treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
