# Generated by Django 6.0.3 on 2026-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_followupscan_ai_economic_followupscan_ai_irrigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_scans_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
