# Generated by Django 6.0.3 on 2026-04-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_customuser_daily_scan_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('wallet_number', models.CharField(max_length=20)),
                ('plan_requested', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fake Payment',
                'verbose_name_plural': 'Fake Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
