# Generated by Django 6.0.3 on 2026-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('expert', 'Expert'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
