# Generated by Django 6.0.3 on 2026-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
