# Generated by Django 6.0.3 on 2026-05-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_messagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='experts/avatars/'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skill tags'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Senior Plant Pathologist', max_length=100),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='website_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='AdminConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='General', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_conversations_as_admin', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_conversations_as_expert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Conversation',
                'verbose_name_plural': 'Admin Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('admin', 'expert')},
            },
        ),
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='experts.adminconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Message',
                'verbose_name_plural': 'Admin Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
