# Generated by Django 6.0.3 on 2026-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_expertprofile_avatar_expertprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_messages/'),
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
