# Generated by Django 6.0.3 on 2026-05-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_adminmessage_image_alter_adminmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, help_text='Emoji reactions: {emoji: [user_ids]}'),
        ),
    ]
