# Generated by Django 6.0.3 on 2026-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view_dashboard', 'Viewed Dashboard'), ('view_user', 'Viewed User'), ('toggle_staff', 'Toggled Staff Status'), ('deactivate_user', 'Deactivated User'), ('activate_user', 'Activated User'), ('delete_scan', 'Deleted Scan'), ('view_scan', 'Viewed Scan'), ('export_data', 'Exported Data'), ('change_plan', 'Changed User Plan')], max_length=50),
        ),
    ]
